services:
  personal-treasury:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ${IMAGE_NAME:-ghcr.io/mosesmc52/personal-treasury}:${TAG:-latest}
    environment:
      PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
      PLAID_SECRET: ${PLAID_SECRET}
      PLAID_ENV: ${PLAID_ENV:-sandbox}
      PLAID_ACCESS_TOKEN: ${PLAID_ACCESS_TOKEN}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      REPORT_FROM_EMAIL: ${REPORT_FROM_EMAIL}
      REPORT_TO_EMAIL: ${REPORT_TO_EMAIL}
