version: 1

settings:
  minimum_allocation: 10
  round_to: 1
  maximum_total_allocation: 5000

accounts:
  checking:
    name: Checking
    type: minimum
    target: 4000
    priority: 10
  savings:
    name: Savings
    type: target
    target: 20000
    priority: 20
    monthly_amount: 1000
  investment:
    name: Investment Account
    type: percentage
    target: 100000
    percentage: 1.0
    priority: 30
  other:
    name: Other Account
    type: ignore
